Repository abonent-21/math_project, pull requests merged in 2024-11, with the labels that each got.

#3 N1-N5 Denis
  ADD_1N_N.py
  ADD_1N_N_test.py
  ADD_NN_N.py
  ADD_NN_N_test.py
  COM_NN_D.py
  COM_NN_D_test.py
  NZER_N_B.py
  NZER_N_B_test.py
  SUB_NN_N.py
  SUB_NN_N_test.py
Labels: понял суть кода George, понял суть кода Alex, готово к слиянию

#2 Create and test z1-z5 functions - George
  ABS_Z_Z.py
  MUL_ZM_Z.py
  POZ_Z_D.py
  TRANS_N_Z.py
  TRANS_Z_N.py
  test_Z1-Z5.py
Labels: понял суть кода George, понял суть кода Mark, понял суть кода Max, понял суть кода Alex, понял суть кода Nikolay, готово к слиянию

#8 Z6 ADD_ZZ_Z & test
  ADD_ZZ_Z.py
  ADD_ZZ_Z_test.py
Labels: понял суть кода Alex, понял суть кода Den, готово к слиянию

#7 Z7 Mark
  SUB_ZZ_Z.py
  SUB_ZZ_Z_test.py
Labels: понял суть кода George, понял суть кода Mark, понял суть кода Alex, готово к слиянию

#6 Z8-Z10 Nickolay
  DIV_ZZ_Z.py
  DIV_ZZ_Z_test.py
  MOD_ZZ_Z.py
  MOD_ZZ_Z_test.py
  MUL_ZZ_Z.py
  MUL_ZZ_Z_test.py
Labels: понял суть кода Alex, понял суть кода Nikolay, готово к слиянию

#10 Q1-4
  INT_Q_B.py
  Q1-4_test.py
  RED_Q_Q.py
  TRANS_Q_Z.py
  TRANS_Z_Q.py
Labels: понял суть кода Alex, готово к слиянию

#11 Q5-Q8_Maks
  ADD_QQ_Q.py
  ADD_QQ_Q_test.py
  DIV_QQ_Q.py
  DIV_QQ_Q_test.py
  MUL_QQ_Q.py
  MUL_QQ_Q_test.py
  SUB_QQ_Q.py
  SUB_QQ_Q_test.py
Labels: need some fix

#12 P4-P6 Mark
  DEG_P_N.py
  LED_P_Q.py
  MUL_Pxk_P.py
  P4-P6_test.py
Labels: понял суть кода Mark, понял суть кода Alex, готово к слиянию

#9 P7-P10 Nickolay
  DIV_PP_P.py
  DIV_PP_P_test.py
  FAC_P_Q.py
  FAC_P_Q_test.py
  MOD_PP_P.py
  MOD_PP_P_test.py
  MUL_PP_P.py
  MUL_PP_P_test.py
Labels: need some fix, понял суть кода Alex
